[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
  -D FC_SERIAL_NUM=2
  -D FC_RX_PIN=16
  -D FC_TX_PIN=17

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_HW_CDC
  -D ARDUINO_USB_MODE=1

[env:esp32c6dev]
platform      = espressif32
board         = esp32-c6-devkitm-1
framework     = arduino
monitor_speed = 115200

build_flags =
  -D MSP_DEBUG_RX
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_HW_CDC
  -D UART1_TX_PIN=5
  -D UART1_RX_PIN=4
