#!/usr/bin/env python3
"""
Generate a C header of MSP message structs from the schema JSON.

Usage:
  python gen_msp_header.py path/to/msp_messages.json [-o msp_messages.h]
"""
import argparse
import json
import re
from pathlib import Path

CTYPE_MAP = {
    "uint8_t": "uint8_t",
    "int8_t": "int8_t",
    "uint16_t": "uint16_t",
    "int16_t": "int16_t",
    "uint32_t": "uint32_t",
    "int32_t": "int32_t",
    "uint64_t": "uint64_t",
    "int64_t": "int64_t",
    "float": "float",
    "char": "char",
    "char[]": "char[]",
}

IDENT_RE = re.compile(r"[^a-zA-Z0-9_]")
CTYPE_SPLIT_RE = re.compile(r"\s*([A-Za-z_]\w*)\s*(?:\[\s*(.*?)\s*\])?\s*$")
PRIMITIVES = set(CTYPE_MAP.values()) | {"char", "float", "double"}
USED_TYPES: set[str] = set()


def norm_ident(s: str) -> str:
    return IDENT_RE.sub("_", s)


def split_ctype(ctype_raw: str):
    m = CTYPE_SPLIT_RE.fullmatch(ctype_raw or "")
    if not m:
        return (ctype_raw, None)
    base = CTYPE_MAP.get(m.group(1), m.group(1))
    size = m.group(2)
    if size is None:
        return (base, None)
    return (base, size)


def field_decl(entry: dict, suffix_comment: str = "") -> str:
    name = norm_ident(entry["name"])
    desc = (entry.get("desc") or "").strip()
    units = (entry.get("units") or "").strip()
    enum_t = entry.get("enum")

    array_flag = bool(entry.get("array"))
    array_size = entry.get("array_size", 0)
    array_size_define = (entry.get("array_size_define") or "").strip()
    ctype_raw = (entry.get("ctype") or "").strip()

    if ctype_raw == "Varies":
        basetype = "uint8_t"
        declarator = f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        cmts = []
        if desc:
            cmts.append(desc)
        if units:
            cmts.append(f"units: {units}")
        if suffix_comment:
            cmts.append(suffix_comment)
        cmt = "  // " + " | ".join(cmts) if cmts else ""
        return f"    {basetype} {declarator};{cmt}"

    if array_flag:
        base = CTYPE_MAP.get(ctype_raw, ctype_raw)
        if array_size_define != "":
            declarator = f"{name}[{array_size_define}]"
        elif isinstance(array_size, int) and array_size > 0:
            declarator = f"{name}[{array_size}]"
        else:
            declarator = f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        basetype = base
    else:
        base_raw, size = split_ctype(ctype_raw)
        base = base_raw
        if size is None:
            basetype, declarator = base, name
        elif size == "":
            basetype, declarator = base, f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        else:
            basetype, declarator = base, f"{name}[{size}]"

    if basetype not in PRIMITIVES and basetype not in ("boxBitmask_t",):
        USED_TYPES.add(basetype)

    cmts = []
    if desc:
        cmts.append(desc)
    if units:
        cmts.append(f"units: {units}")
    if enum_t:
        cmts.append(f"Enum: {enum_t}")
    if array_flag and array_size_define:
        cmts.append(f"length via {array_size_define}")
    if suffix_comment:
        cmts.append(suffix_comment)
    cmt = "  // " + " | ".join(cmts) if cmts else ""
    return f"    {basetype} {declarator};{cmt}"


def emit_header_preamble():
    return """#pragma once
// Auto-generated by gen_msp_header.py. Do not edit by hand.

#include <stdint.h>
#include "msp_protocol.h"
#include "msp_types.h"

#if !defined(MSP_PROTOCOL_VERSION)
# error "msp_protocol.h must be present and define protocol macros"
#endif

#if defined(_MSC_VER)
#  pragma pack(push, 1)
#  define MSP_PACKED
#else
#  define MSP_PACKED __attribute__((__packed__))
#endif

// Placeholder size for variable length arrays when the exact length is unknown at compile time
#ifndef UNDEFINED_LEN_ARRAY_PLACEHOLDER
#define UNDEFINED_LEN_ARRAY_PLACEHOLDER 1
#endif

"""


def emit_header_postamble():
    return """
#if defined(_MSC_VER)
#  pragma pack(pop)
#endif
#undef MSP_PACKED
"""


def emit_struct(name: str, payload: list, parent_msg: dict) -> str:
    lines = []
    lines.append("typedef struct MSP_PACKED {")

    for ent in payload:
        if isinstance(ent, dict) and ent.get("repeating") and "payload" in ent:
            arr_name = norm_ident(ent.get("name", "items"))
            rep = ent.get("repeating")
            if isinstance(rep, int) and rep > 0:
                bracket = f"[{rep}]"
            elif isinstance(rep, str) and rep.strip():
                rep_clean = rep.strip()
                if any(ch.islower() for ch in rep_clean):
                    bracket = "[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
                else:
                    bracket = f"[{rep_clean}]"
            else:
                bracket = "[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"

            inner_payload = ent["payload"]
            if (
                isinstance(inner_payload, list)
                and len(inner_payload) == 1
                and isinstance(inner_payload[0], dict)
                and "payload" in inner_payload[0]
            ):
                inner_payload = inner_payload[0]["payload"]

            lines.append(f"    struct MSP_PACKED {{")
            for sub in inner_payload:
                lines.append(field_decl(sub))
            lines.append(f"    }} {arr_name}{bracket};  // repeating: {rep}")
            continue

        lines.append(field_decl(ent))

    lines.append(f"}} {name};\n")
    return "\n".join(lines)


def pick_variant_suffix(key: str) -> str:
    s = key.strip()
    s = (
        s.replace(">=", "ge")
        .replace("==", "eq")
        .replace("<=", "le")
        .replace(">", "gt")
        .replace("<", "lt")
        .replace(" ", "_")
    )
    s = IDENT_RE.sub("_", s)
    return "_" + s


def main():
    parser = argparse.ArgumentParser(description="Generate MSP C header from schema JSON.")
    parser.add_argument("schema", help="Path to msp_messages.json")
    parser.add_argument("-o", "--out", default="msp_messages.h", help="Output header path (default: msp_messages.h)")
    parser.add_argument("--needed-types", help="Optional output path for referenced support types")
    args = parser.parse_args()

    root = json.loads(Path(args.schema).read_text())
    data = root["messages"] if "messages" in root else root
    USED_TYPES.clear()
    out = []
    out.append(emit_header_preamble())

    for msg_name, msg in data.items():
        desc = (msg.get("description") or "").strip()
        notes = (msg.get("notes") or "").strip()
        code = int(msg.get("code"))
        mspv = int(msg.get("mspv") or (1 if code <= 255 else 2))
        reply = msg.get("reply") or {}
        request = msg.get("request") or {}
        variants = msg.get("variants")

        safe_msg_name = norm_ident(msg_name)
        base_struct = f"{safe_msg_name}_reply_t"
        base_req_struct = f"{safe_msg_name}_request_t"

        out.append(f"// {msg_name} (MSPv{mspv})")
        if desc:
            out.append(f"// {desc}")
        if notes:
            out.append(f"// Notes: {notes}")
        out.append("")

        if variants:
            for vkey, v in variants.items():
                suffix = pick_variant_suffix(vkey)
                if "request" in v and v["request"] and "payload" in v["request"]:
                    out.append(emit_struct(base_req_struct + suffix, v["request"]["payload"], msg))
                if "payload" in v:
                    out.append(emit_struct(base_struct + suffix, v["payload"], msg))
            continue

        if request and "payload" in request and request["payload"]:
            out.append(emit_struct(base_req_struct, request["payload"], msg))
        if reply and "payload" in reply and reply["payload"]:
            out.append(emit_struct(base_struct, reply["payload"], msg))

    out.append(emit_header_postamble())
    output_path = Path(args.out)
    temporary = output_path.with_suffix(output_path.suffix + ".tmp")
    temporary.write_text("\n".join(out))
    temporary.replace(output_path)

    if args.needed_types:
        Path(args.needed_types).write_text("\n".join(sorted(USED_TYPES)) + "\n")


if __name__ == "__main__":
    main()
