#!/usr/bin/env python3
"""
Generate the INAV enum types referenced by the MSP schema.

Usage:
    python gen_all_enums.py inav_enums.json --schema msp_messages.json -o all_enums.h
"""

import argparse
import json
import re
from pathlib import Path


def collect_schema_types(value, enum_storage, size_symbols):
    if isinstance(value, dict):
        enum_name = value.get("enum")
        ctype = value.get("ctype")
        if enum_name and ctype:
            previous = enum_storage.get(enum_name)
            if previous and previous != ctype:
                raise ValueError(f"{enum_name} uses both {previous} and {ctype}")
            enum_storage[enum_name] = ctype
        size_expression = value.get("array_size_define", "")
        size_symbols.update(re.findall(r"\b[A-Za-z_]\w*\b", size_expression))
        for child in value.values():
            collect_schema_types(child, enum_storage, size_symbols)
    elif isinstance(value, list):
        for child in value:
            collect_schema_types(child, enum_storage, size_symbols)


def main() -> None:
    parser = argparse.ArgumentParser(description="Render MSP-referenced INAV enums as a C header")
    parser.add_argument("source", type=Path, help="Path to inav_enums.json")
    parser.add_argument("--schema", type=Path, required=True, help="Path to msp_messages.json")
    parser.add_argument("--include", action="append", default=[], dest="extra_enums")
    parser.add_argument("-o", "--out", type=Path, default=Path("all_enums.h"))
    args = parser.parse_args()

    enum_root = json.loads(args.source.read_text())
    enums = enum_root["enums"] if "enums" in enum_root else enum_root
    schema_root = json.loads(args.schema.read_text())
    schema = schema_root["messages"] if "messages" in schema_root else schema_root
    enum_storage = {}
    size_symbols = set()
    collect_schema_types(schema, enum_storage, size_symbols)
    size_enums = {
        enum_name
        for enum_name, entries in enums.items()
        if size_symbols & set(entries)
    }
    selected = sorted((set(enum_storage) & set(enums)) | size_enums | set(args.extra_enums))
    missing = sorted(set(enum_storage) - set(enums))

    lines = [
        "#pragma once",
        "// Generated by gen_all_enums.py from the enums used by msp_messages.json.",
        "",
        "#include <stdint.h>",
        "",
    ]
    member_owners = {}
    for enum_name in selected:
        entries = enums[enum_name]
        source = entries.get("_source")
        if source:
            lines.append(f"// Source: {source}")
        lines.append(f"typedef enum {enum_name} {{")
        for member, value in entries.items():
            if member == "_source":
                continue
            owner = member_owners.get(member)
            if owner:
                raise ValueError(f"enumerator {member} is present in both {owner} and {enum_name}")
            member_owners[member] = enum_name
            condition = ""
            if isinstance(value, list):
                raw_value, condition_name = value
                if condition_name:
                    condition = f" // requires {condition_name}"
            else:
                raw_value = value
            assignment = f" = {raw_value}" if raw_value != "" else ""
            lines.append(f"    {member}{assignment},{condition}")
        lines.append(f"}} {enum_name};")
        lines.append("")

    for enum_name in missing:
        lines.append(
            f"// {enum_name} is named by the schema but absent from inav_enums.json; "
            "the schema wire type is retained."
        )
        lines.append(f"typedef {enum_storage[enum_name]} {enum_name};")
        lines.append("")

    temporary = args.out.with_suffix(args.out.suffix + ".tmp")
    temporary.write_text("\n".join(lines))
    temporary.replace(args.out)
    print(
        f"Wrote {args.out}: enums={len(selected)} "
        f"schema_type_aliases={len(missing)}"
    )


if __name__ == "__main__":
    main()
